# Generated by Django 4.1 on 2022-08-25 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('NO', 'Normal'), ('FI', 'Fighting'), ('FL', 'Flying'), ('PO', 'Poison'), ('GR', 'Ground'), ('RO', 'Rock'), ('BU', 'Bug'), ('GH', 'Ghost'), ('ST', 'Steel'), ('FI', 'Fire'), ('WA', 'Water'), ('GR', 'Grass'), ('EL', 'Electric'), ('PS', 'Psychic'), ('IC', 'Ice'), ('DR', 'Dragon'), ('DA', 'Dark'), ('FA', 'Fairy'), ('??', '???')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('type_one', models.CharField(choices=[('NO', 'Normal'), ('FI', 'Fighting'), ('FL', 'Flying'), ('PO', 'Poison'), ('GR', 'Ground'), ('RO', 'Rock'), ('BU', 'Bug'), ('GH', 'Ghost'), ('ST', 'Steel'), ('FI', 'Fire'), ('WA', 'Water'), ('GR', 'Grass'), ('EL', 'Electric'), ('PS', 'Psychic'), ('IC', 'Ice'), ('DR', 'Dragon'), ('DA', 'Dark'), ('FA', 'Fairy'), ('??', '???')], max_length=2)),
                ('type_two', models.CharField(blank=True, choices=[('NO', 'Normal'), ('FI', 'Fighting'), ('FL', 'Flying'), ('PO', 'Poison'), ('GR', 'Ground'), ('RO', 'Rock'), ('BU', 'Bug'), ('GH', 'Ghost'), ('ST', 'Steel'), ('FI', 'Fire'), ('WA', 'Water'), ('GR', 'Grass'), ('EL', 'Electric'), ('PS', 'Psychic'), ('IC', 'Ice'), ('DR', 'Dragon'), ('DA', 'Dark'), ('FA', 'Fairy'), ('??', '???')], max_length=2)),
                ('evolves_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.pokemon')),
            ],
        ),
    ]
