# Generated by Django 4.0.5 on 2022-08-31 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('NOR', 'Normal'), ('FIG', 'Fighting'), ('FLY', 'Flying'), ('POI', 'Poison'), ('GRO', 'Ground'), ('ROC', 'Rock'), ('BUG', 'Bug'), ('GHO', 'Ghost'), ('STE', 'Steel'), ('FIR', 'Fire'), ('WAT', 'Water'), ('GRA', 'Grass'), ('ELE', 'Electric'), ('PSY', 'Psychic'), ('ICE', 'Ice'), ('DRA', 'Dragon'), ('DAR', 'Dark'), ('FAI', 'Fairy'), ('???', '???')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('type_one', models.CharField(choices=[('NOR', 'Normal'), ('FIG', 'Fighting'), ('FLY', 'Flying'), ('POI', 'Poison'), ('GRO', 'Ground'), ('ROC', 'Rock'), ('BUG', 'Bug'), ('GHO', 'Ghost'), ('STE', 'Steel'), ('FIR', 'Fire'), ('WAT', 'Water'), ('GRA', 'Grass'), ('ELE', 'Electric'), ('PSY', 'Psychic'), ('ICE', 'Ice'), ('DRA', 'Dragon'), ('DAR', 'Dark'), ('FAI', 'Fairy'), ('???', '???')], max_length=3)),
                ('type_two', models.CharField(blank=True, choices=[('NOR', 'Normal'), ('FIG', 'Fighting'), ('FLY', 'Flying'), ('POI', 'Poison'), ('GRO', 'Ground'), ('ROC', 'Rock'), ('BUG', 'Bug'), ('GHO', 'Ghost'), ('STE', 'Steel'), ('FIR', 'Fire'), ('WAT', 'Water'), ('GRA', 'Grass'), ('ELE', 'Electric'), ('PSY', 'Psychic'), ('ICE', 'Ice'), ('DRA', 'Dragon'), ('DAR', 'Dark'), ('FAI', 'Fairy'), ('???', '???')], max_length=3)),
                ('evolves_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolves_into', to='pokedex.pokemon')),
                ('found_in', models.ManyToManyField(blank=True, related_name='can_be_found', to='pokedex.location')),
                ('learnable', models.ManyToManyField(blank=True, related_name='can_learn', to='pokedex.move')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.profile')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.profile'),
        ),
        migrations.AddField(
            model_name='location',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.profile'),
        ),
    ]
