# Generated by Django 4.1 on 2022-09-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='found_in',
            field=models.ManyToManyField(blank=True, related_name='can_find', to='pokedex.location'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='learnable',
            field=models.ManyToManyField(blank=True, related_name='can_be_learned_by', to='pokedex.move'),
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.profile')),
            ],
        ),
    ]
