# Generated by Django 4.1 on 2022-08-25 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_alter_move_type_alter_pokemon_type_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolves_into', to='pokedex.pokemon'),
        ),
    ]
