# Generated by Django 4.1 on 2022-08-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0003_alter_pokemon_evolves_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='learnable',
            field=models.ManyToManyField(to='pokedex.pokemon'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolves_into', to='pokedex.pokemon'),
        ),
    ]
