# Generated by Django 4.1 on 2022-09-12 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0004_findable_remove_pokemon_found_in_pokemon_can_find_in_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pokemon',
            name='abilities',
            field=models.ManyToManyField(blank=True, related_name='can_be_possessed_by', through='pokedex.Capable', to='pokedex.ability'),
        ),
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='move',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='can_find_in',
            field=models.ManyToManyField(blank=True, related_name='can_find', through='pokedex.Findable', to='pokedex.location'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='can_learn',
            field=models.ManyToManyField(blank=True, related_name='can_be_learned_by', through='pokedex.Learnable', to='pokedex.move'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='capable',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.ability'),
        ),
        migrations.AddField(
            model_name='capable',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.pokemon'),
        ),
    ]
