# Generated by Django 4.1 on 2022-09-26 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0007_alter_profile_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='profile',
            name='unique_profiles',
        ),
    ]
