# Generated by Django 4.1 on 2022-10-17 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0010_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
