# Generated by Django 4.0.5 on 2022-11-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0011_pokemon_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolves_into',
            field=models.ManyToManyField(blank=True, to='pokedex.pokemon'),
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='evolves_from',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ManyToManyField(blank=True, to='pokedex.pokemon'),
        ),
    ]
