# Generated by Django 4.0.5 on 2022-11-07 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0012_pokemon_evolves_into_remove_pokemon_evolves_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolves_from',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokedex.pokemon'),
        ),
    ]
