# Generated by Django 4.0.5 on 2022-11-08 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0016_remove_pokemon_evolves_from_pokemon_evolves_from'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolves_into',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='evolves_from',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolves_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolves_into', to='pokedex.pokemon'),
        ),
    ]
